#!/bin/bash
#
# microconf is a simple tool for building simple configure scripts.
#
# Copyright (C) 2021 Olaf Kirch <okir@suse.de>
#

uc_supportfiles_dir=/usr/share/microconf

uc_default_modules="builtin platform defaults"

function uc_fatal {

	echo "$@" >&2
	exit 2
}

uc_configure=
for __dir in "$@" "."; do
	__script="$__dir/configure"
	if [ -x "$__script" ]; then
		uc_configure=$__script
		uc_sourcedir=$__dir
		break
	fi
done

if [ -z "$uc_configure" ]; then
	uc_fatal "Unable to find your configure script"
fi

##################################################################
# Extract list of required modules from configure script
# These are provided by the user in this fashion:
#
#  microconf:begin
#  version 1.2.3.4
#  require python3
#  require ruby
#  microconf:end
##################################################################
__uc_requires=""
__uc_version=""
__uc_with_options=""
__uc_bool_options=""
__uc_block_start_found=false
__uc_block_end_found=false
while read line; do
	expr "$line" : " *# *microconf:begin.*" >/dev/null || continue

	__uc_block_start_found=true
	while read line; do
		if expr "$line" : " *# *microconf:end.*" >/dev/null; then
			__uc_block_end_found=true
			break
		fi

		set -- $line
		if [ "$1" != "#" ]; then
			continue
		fi

		word=$2; shift 2
		case $word in
		require)
			__uc_requires="$__uc_requires $*";;
		version)
			if [ $# -ne 1 ]; then
				uc_fatal "Bad number of arguments in $line"
			fi
			__uc_version="$1";;
		with)
			__uc_with_options="$__uc_with_options $1"
			export uc_with_$1="$2"
			;;
		enable)
			__uc_bool_options="$__uc_bool_options $1"
			var_name=$(echo $1 | tr .- _)
			export uc_enable_$var_name=true;;
		disable)
			__uc_bool_options="$__uc_bool_options $1"
			var_name=$(echo $1 | tr .- _)
			export uc_enable_$var_name=false;;
		*)
			uc_fatal "Cannot handle line in microconf block: $line";;
		esac
		continue
	done
done < $uc_configure

if [ -z "$__uc_version" ]; then
	if [ ! -r "$uc_sourcedir/RELEASE" ]; then
		uc_fatal "You need to specify a version number; either in the configure script, or in a RELEASE file in $uc_sourcedir"
	fi

	. "$uc_sourcedir/RELEASE"
	if [ -z "$VERSION" ]; then
		uc_fatal "Your RELEASE file does not seem to define a VERSION"
	fi

	__uc_version="$VERSION"
fi

if ! $__uc_block_start_found; then
	uc_fatal "$uc_configure: no microconf:begin line found"
fi
if ! $__uc_block_end_found; then
	uc_fatal "$uc_configure: no microconf:end line found"
fi

echo "$uc_configure requires these modules: $__uc_requires"

##################################################################
uc_stage1_counter=0
uc_stage2_counter=0
uc_stage3_counter=0

function uc_stage_index {

	stage=$1

	__uc_index=$((uc_${stage}_counter++))
	__uc_index=$(printf "%02u" $__uc_index)
}

function uc_maybe_install_module {

	stage=$1
	module=$2
	script=$3
	shift 3

	path="$uc_supportfiles_dir/modules/$module/$script"
	if [ -f "$path" ]; then
		uc_stage_index $stage

		test -d "$uc_installdir/$stage" || mkdir -vp "$uc_installdir/$stage"
		cp -v "$path" "$uc_installdir/$stage/$__uc_index-$module"

		# Process template
		if [ $# -ne 0 ]; then
			"$@" "$uc_installdir/$stage/$__uc_index-$module"
		fi
	fi
}

function uc_module_requires {

	module=$1

	path="$uc_supportfiles_dir/modules/$module/requires"
	if [ -f "$path" ]; then
		cat $path
	fi
}

function uc_maybe_install_part {

	script=$1
	mode=$2

	path="$uc_supportfiles_dir/parts/$script"
	if [ -f "$path" ]; then
		test -d "$uc_installdir" || mkdir -vp "$uc_installdir"
		cp -v "$path" "$uc_installdir/$script"
		if [ -n "$mode" ]; then
			chmod $mode "$uc_installdir/$script"
		fi
	fi
}

function uc_process_module {

	local module=$1

	declare -gA __uc_module_seen

	if [ -n "${__uc_module_seen[$module]}" ]; then
		echo "$module already installed"
		return
	fi

	let __uc_module_seen[$module]=1

	for req in $(uc_module_requires $module); do
		uc_process_module $req
	done

	uc_maybe_install_module stage1 $module options
	uc_maybe_install_module stage2 $module functions
	uc_maybe_install_module stage3 $module check
	uc_maybe_install_module stage4 $module subst
}

function uc_process_with_option {

	with_name=$1

	uc_maybe_install_module stage1 with-option options \
		uc_process_with_template $with_name
	uc_maybe_install_module stage2 with-option functions \
		uc_process_with_template $with_name
	uc_maybe_install_module stage3 with-option check \
		uc_process_with_template $with_name
	uc_maybe_install_module stage4 with-option subst \
		uc_process_with_template $with_name
}

function uc_process_with_template {

	with_name=$1
	path=$2

	var_name=$(echo $with_name | tr .- _)
	eval with_value="\$uc_with_$var_name"
	sed -i -e "s:@OPTION_NAME@:$with_name:" \
	       -e "s:@OPTION_VALUE@:$with_value:" \
		"$path"
}

function uc_process_boolean_option {

	bool_name=$1

	uc_maybe_install_module stage1 bool-option options \
		uc_process_boolean_template $bool_name
	uc_maybe_install_module stage2 bool-option functions \
		uc_process_boolean_template $bool_name
	uc_maybe_install_module stage3 bool-option check \
		uc_process_boolean_template $bool_name
	uc_maybe_install_module stage4 bool-option subst \
		uc_process_boolean_template $bool_name
}

function uc_process_boolean_template {

	bool_name=$1
	path=$2

	var_name=$(echo $bool_name | tr .- _)
	eval bool_value="\$uc_enable_$var_name"
	sed -i -e "s:@OPTION_NAME@:$bool_name:" \
	       -e "s:@OPTION_VALUE@:$bool_value:" \
		"$path"
}

uc_installdir="$uc_sourcedir/microconf"

rm -rf "$uc_installdir"

uc_maybe_install_part prepare
uc_maybe_install_part check
uc_maybe_install_part subst +x

for module in $uc_default_modules; do
	uc_process_module $module
done

for option in $__uc_bool_options; do
	uc_process_boolean_option $option
done

for option in $__uc_with_options; do
	uc_process_with_option $option
done

for module in $__uc_requires; do
	uc_process_module $module
done

echo "uc_version=$__uc_version" > "$uc_installdir/version"

if [ -d "$uc_sourcedir/.git" ]; then
	echo "sedscript" >"$uc_installdir/.gitignore"
fi
